services:
  - type: web
    name: cyberforge-api
    env: node
    plan: free
    rootDir: Umurava_api
    buildCommand: npm install && npx prisma db push
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: cyberforge-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000

databases:
  - name: cyberforge-db
    plan: free